### PR TITLE
Improve code readability

### PR DESCRIPTION
**Pull request by DevBonBon**
So this is a bit more of a subjective improvement.
This doesn't change the functionality of the code, and both this branch and master produce minified builds of the same size.
I made these changes based on few reasons
- To improve the maintainability of the project
- To make it easier for new people to come by, understand the code, and make contributions
- Comments and code style don't affect or bloat the minified builds (the only ones people should really use)
- [JS semistandard](https://github.com/Flet/semistandard) closely resembled the existing code style (well, the semicolons anyways :P)

Let me know you what you think, especially about the `npm` commands

### CODE REVIEW

**Comment by KoryNunn** [comment]
I like the added comments.

I want to keep the file 4-spaced.

I want to keep semicolons.

I have effectively no interest in conforming to a standard as they generally bring unpragmatic rigidity to style that hurts understandability for the sake of consistency.

As for the other changes, I'd have to see what was done specifically, which is hard, since almost everything has changed. I'd recommend sending *VERY* incremental PR's so that it's easier to decide what should or should not be merged.

**Comment by DevBonBon** [comment]
Sorry about the poor incrementality,  I auto-linted the files, which pretty much touched everything.
I'll move the js-semistandard changes to last, so you can ignore them if you want to, but it does follow the current style rather closely. The three changes it does are:
- 2-spaces instead of 4
- consistent spacing around braces and such
- variables are all declared with separate `var` calls, which doesn't really matter as uglifyjs picks that up and makes them into a single declaration again.
The main benefit would be the automatic linting, but as I said I'll move the commits

**Comment by KoryNunn** [comment]
I'm ok with brace spacing and split vars, but I'm absolutely against 2 spaced tabs :)

**Comment by DevBonBon** [comment]
How would you feel about [happiness](https://github.com/JedWatson/happiness)? It would give the benefit of automatic linting, while using tabs instead of spaces. Tabs could then be configured to display as 4 spaces in the editor

**Comment by DevBonBon** [comment]
Ok, just making sure I guess :D I'll remove the Package changes and make this ready for a merge

**Comment by DevBonBon** [comment]
Removed Package and indentation changes. I didn't bother editing the tests, as that's done in another pr

**Pull request merged**
