### PR TITLE
Add ESM support

### PR DESCRIPTION
**Pull request by lpellegr**
Browsers have improved a lot over the past years and it is now possible to do modern web development without requiring any build tools (i.e. buildless). 

We are adding ESM support to Prose Mirror and as a requirement, transitive dependencies need to provide an ESM version. Crel is one of these dependencies:

https://discuss.prosemirror.net/t/prose-mirror-buildless-esm-support/2322

This PR aims to generate an ESM version of the source code before packaging.

### CODE REVIEW

**Comment by lpellegr** [comment]
@KoryNunn Do you think this could be merged and released after a review?

**Comment by KoryNunn** [comment]
Hey @lpellegr thanks for the PR,

Would it be possible to use package.json "files" instead of .npmignore? it's very easy to shoot yourself in the foot with .npmignore.

If not, I'll do it, but it might take me a few days to get around to it.

**Comment by lpellegr** [comment]
@KoryNunn Thanks for your answer. I have applied your suggestion.

Here is the resulting tarball content:

> === Tarball Contents === 
> 4.9kB crel.js     
> 696B  crel.min.js 
> 1.2kB package.json
> 3.3kB README.md   
> 4.8kB crel.mjs    
> 1.1kB LICENSE.txt

**Comment by KoryNunn** [comment]
@lpellegr is there any chance you could send a PR adding to the README about how to use this?

**Comment by lpellegr** [comment]
@KoryNunn Done in https://github.com/KoryNunn/crel/pull/53. Do you plan a release soon?

**Comment by KoryNunn** [comment]
4.1.0 released.

**Comment by lpellegr** [comment]
Great. Thanks a lot!

**Pull request merged**
