### PR TITLE
Add more and improve testing

### PR DESCRIPTION
**Pull request by DevBonBon**
This does a couple of things:
- Update test related packages to latest versions
- use opn-cli to open test.html
- changes to test.html (see fb8cd052ce8040b383861256427d0e14bcc822ea and 722ef3d3da518902a3993f8d1a02be0a19316440)
- Make existing tests more explicit and comprehensive
- remove `end()` calls as requested
- add 3 new tests (see 67048effb16d3145f550c1f496df2465e23271c9, 731210bcef309ca6d3fa80bb940bc4e89688721f and 52503f5721fd26c2e6591b03d07aa497cf41958f)

Some things still need work, mainly the proxy part, but I'll leave that to another pr, this is big enough as is. I left comments about these in the code.

Stuff to consider
- Installing [tape-catch](https://github.com/michaelrhodes/tape-catch)
Currently not that useful, but will be if testing for garbage input becomes a thing (#43)
- Code coverage tools
I don't know how essential these would be in the long run in a small project like Crel, but at least having a look locally should give important insight on how comprehensive the tests currently are

### CODE REVIEW

**Comment by DevBonBon** [comment]
Let me know how you feel about handling weird object keys in the attributes. Implementing that would be kinda dirty atm.

**Comment by KoryNunn** [comment]
I don't want to lump work on you but at some stage I'd like to remove the `t.end()` calls, so if it makes your life easier, feel free :)

**Comment by DevBonBon** [comment]
Rebased! No more extra test grouping and removed those `end()` calls. I also left out the invalid attributes object tests, as I don't think crel should worry about them anyways. Also made some changes to `npm test` as some people don't use chrome :P

**Comment by KoryNunn** [comment]
Most of the tests fail, and not all of the tests finish.

**Comment by DevBonBon** [comment]
Most of the added tests concern handling invalid input, which crel doesn't do at all atm. The tests crash at the property manipulation, which is not implemented. I should probably move them over to #35, but for now you can just comment them out to see the rest of the tests.

**Comment by DevBonBon** [comment]
Rebased, removed property in invalid input tests, as those will be added in their own prs. All tests now run, and luckilly crel doesn't fail any of them

**Comment by DevBonBon** [comment]
@KoryNunn could you give this another look now that I've tidied it up

**Comment by KoryNunn** [comment]
Awesome work, thanks!

**Pull request merged**
